language: python
python:
  - "2.7"
  - "3.5"
# whitelist of git branches to build
branches:
  only:
    - master
    - python3
# install required system packages
addons:
  apt:
    packages:
    - python-dev
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install pyftpdlib pytest-xdist pytest-cov coveralls
# command to run tests
script:
  - make test PYTESTOPTS="--tb=short --cov=linkcheck" TESTS="tests/test_*.py tests/configuration/test_*.py tests/logger/test_*.py tests/checker/test_httpbin.py"
  - python setup.py install
# do not send emails of broken builds
notifications:
  email: false
after_script:
  - coveralls
