language: python
python:
  - "2.7"
# whitelist of git branches to build
branches:
  only:
    - master
# install required system packages
addons:
  apt:
    packages:
    - python-dev
    - qt4-dev-tools
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install pyftpdlib pytest-xdist
# command to run tests
script: make test PYTESTOPTS="--tb=short" TESTS="tests/test_*.py tests/configuration/test_*.py tests/logger/test_*.py tests/checker/test_httpbin.py"
# do not send emails of broken builds
notifications:
  email: false
